### ISSUE TITLE
Payments: method is an optional field

### ISSUE THREAD

**Issue by skamoen** [stil4m/mollie-api#12]
In the Mollie API, the "method" field is optional (https://www.mollie.com/nl/docs/reference/payments/create), as the user is presented with a method selection screen when this value isn't present.

Currently, `method` is a non-optional field in the api client, which makes method selection on Mollies side a bit hard. Setting this value to `null` gives the desired effect on Mollies side, but gives nullpointers in the api client.

**Comment by stil4m** [comment]
Can you provide a stacktrace?

**Comment by skamoen** [comment]
My apologies, it seems the nullpointer had another cause, and incidently occured right after I tried `null` for the method String. Everything is working just fine.
