### ISSUE TITLE
Refunds API currently broken

### ISSUE THREAD

**Issue by stil4m** [stil4m/mollie-api#20]
The refunds API is currently broken. This is due to a XML response that Mollie returns instead of an JSON response. See the build history #332 > [https://travis-ci.org/stil4m/mollie-api/builds](https://travis-ci.org/stil4m/mollie-api/builds)

**Comment by Daanvm** [comment]
Hi @stil4m,
We just fixed the HTML-response. The API returned an error, but of course this should have been a JSON error.

**Comment by stil4m** [comment]
Reran the build. Seems to be fixed
