### ISSUE TITLE
Should the object mapper be more forgiving?

### ISSUE THREAD

**Issue by stil4m** [stil4m/mollie-api#25]
Deserialization fails when unrecognised fields are added to the API. Now we notice this directly in the nightly build. But when you use the Api in production it would be nice that the added fields are just ignored.

An approach would be to:
- make the default object mapper to be more forgiving
- make the object mapper that is being used in the integration tests as strict as it currently is.

Any ideas on this?

**Comment by tubbynl** [comment]
in my opinion the adding of new fields in the API should not result in breaking existing production deployments of the mollie-client so i prefer making the default object mapper more forgiving and having a nightly build running a strict object mapper would be nice to detect api changes early

but if the latter happens really often it might backfire on it's purpose

maybe @jcassee also has a view on this

**Comment by tubbynl** [comment]
Daamvm (from Mollie) in #23 

> You're right stil4m, the resource attribute is only added for payments which have an API customer. We wanted to make the endpoints more consistent by adding the resource attribute to each response. We didn't want to break existing implementations, so that's why wo only added it to payments with a customer.
> 
> I can imagine it's confusing the way it's right now. I'll report it internally, we can at least update the docs.
> 
> Further would I recommend ignoring unknown fields from our API. We might occasionally [add new fields](https://www.mollie.com/en/docs/changelog), for example to the payment details object for new payment types. Note that it will never be backwards incompatible when you ignore the unknown fields.

**Comment by stil4m** [comment]
Fixed with #29
