### ISSUE TITLE
Recurring payment integration test

### ISSUE THREAD

**Issue by tubbynl** [stil4m/mollie-api#32]
An recurring payment requires a correct mandate on the customer

In a normal flow this is achieved by an customer completing a firstPayment successfully (see CustomerPaymentIntegrationTest.testCreateFirstRecurringPayment for creation).

The (test) problem i have is i cannot complete that first payment using API; i've created CustomerPaymentIntegrationTest.testCreateRecurringPayment to indicate that problem and i am contacting Mollie to see if there's ~~a sneaky way~~ test api to fake this.

If i manually follow the paymentUrl of the first payment and complete it it will result in a jackson deserialisation issue (due to the strict object mapper) on the resulting recurring payment so testing this really makes sense :)

@Daanvm this has also been issued via info@mollie.com

**Comment by stil4m** [comment]
Fixed with #33
