### ISSUE TITLE
Unrecognized field "canBeCancelled"

### ISSUE THREAD

**Issue by dfranssen** [stil4m/mollie-api#48]
It seems the API has been changed on 29/8/2017 (https://www.mollie.com/nl/developers/changelog)

v2.6.0 and also 2.6.2 are failing with:

`com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "canBeCancelled" (class nl.stil4m.mollie.domain.Payment), not marked as ignorable (23 known properties: "expiredDatetime", "method", "details", "mode", "profileId", "paidDatetime", "cancelledDatetime", "resource", "amountRefunded", "status", "expiryPeriod", "recurringType", "amount", "customerId", "locale", "id", "description", "amountRemaining", "createdDatetime", "metadata", "links", "countryCode", "mandateId"])
 at [Source: org.apache.http.conn.EofSensorInputStream@710636b0; line: 1, column: 453] (through reference chain: nl.stil4m.mollie.domain.Payment["canBeCancelled"])`

Bypassed it by configuring `objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);`

But the domain model should be kept in sync with API in order to use those new API properties/features.

**Comment by stil4m** [comment]
I know CI is failing due how the deserialization is configured in the tests. Please read the part on `FAIL_ON_UNKNOWN_PROPERTIES` in the README about why it is configured as it is in the library itself. You do **not** want the people from Mollie to break your application without being in control.

Atm I am not really busy with this library. Not that much time. But I will ship new versions and accept PRs.

**Comment by tubbynl** [comment]
i needed the https://www.mollie.com/en/docs/reference/payments/delete function and came across this property and added it (see #50)

**Comment by tubbynl** [comment]
heb de andere deserialize meldingen ook ff weggepoetst @stil4m , dat zit allemaal in #49 

de testjes die nu nog mis gaan hebben te maken met dat de payments methods op de test api key volgens mij gewijzigd zijn (en dat creditcard daar niet meer bij staat)

i think you need to re-add creditcard

**Comment by tubbynl** [comment]
w00t; green build \o/
