### ISSUE TITLE
add support for cancel payment

### ISSUE THREAD

**Issue by tubbynl** [stil4m/mollie-api#50]
it depends on payment#canBeCancelled

but i can't figure out how to create a payment that canBeCancelled ;)

https://www.mollie.com/en/docs/reference/payments/delete

**Comment by tubbynl** [comment]
i currently only test the cancelling an payment which cannot be cancelled, i need to figure out how to create a payment which can be cancelled

**Comment by Daanvm** [comment]
Payments with method `banktransfer` can be cancelled as long as they're not paid or expired.

**Comment by tubbynl** [comment]
Tnx! I’ll add a testcase for that

**Comment by tubbynl** [comment]
Tnx @Daanvm , i added tests to PR #49

**Comment by stil4m** [comment]
Thanks @tubbynl!
