### ISSUE TITLE
missing issuer on creating payment

### ISSUE THREAD

**Issue by jvanoosterom** [stil4m/mollie-api#9]
The mollie api allows for optional parameters parameters in the case of 'idea'
 the 'issuer' (bank)

This is missing in the createPayment.

**Comment by stil4m** [comment]
Thanks for the issue jvanoosterom.
I guess you mean `ideal` instead of `idea`?

I will look at it when I got time, can't promise anything yet. If you want, you can create a PR.

**Comment by jvanoosterom** [comment]
yes 'ideal' ofcourse;)
we now created a local version with an extra param issuer, but that is not complete for the other optional params for other payment methods.

**Comment by stil4m** [comment]
Will add subtypes per payment method that support the additional arguments. Will ship before Monday with an `1.5.0` release.

**Comment by stil4m** [comment]
Added concrete payment types in `nl.stil4m.mollie.domain.subpayments`. Probably you guys are interested in `nl.stil4m.mollie.domain.subpayments.ideal.CreateIdealPayment`.

**Comment by stil4m** [comment]
Released new version to [https://github.com/stil4m/maven-repository](https://github.com/stil4m/maven-repository)

**Comment by jvanoosterom** [comment]
thx!!
